# Generated by Django 4.2.3 on 2023-08-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GaBean', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='close_hours',
            field=models.CharField(default='정보 없음', max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='content',
            field=models.CharField(default='', max_length=300),
        ),
    ]
