# Generated by Django 4.2.3 on 2023-08-31 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GaBean', '0002_restaurant_close_hours_restaurant_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant_time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_week', models.CharField(default='', max_length=100)),
                ('open_hours', models.CharField(default='정보 없음', max_length=100)),
                ('close_hours', models.CharField(default='정보 없음', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='close_hours',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='open_hours',
        ),
    ]
