# Generated by Django 4.2.3 on 2023-08-31 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GaBean', '0003_restaurant_time_remove_restaurant_close_hours_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Building',
        ),
        migrations.RemoveField(
            model_name='restaurant_time',
            name='close_hours',
        ),
        migrations.RemoveField(
            model_name='restaurant_time',
            name='open_hours',
        ),
        migrations.AddField(
            model_name='restaurant_time',
            name='name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='GaBean.restaurant'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
